### ISSUE TITLE
Heroku > Ghost > Netlify: Content does not mirror

### ISSUE THREAD

**Issue by seichris** [styxlab/gatsby-theme-try-ghost#160]
I am running ghost on Heroku.  And run `gatsby-starter-try-ghost` in Netlify.

`.ghost.json` has the API keys. Changing content is triggering the hooks.
And build is working fine. But I only see the standard content, not the new posts.

Heroku version: https://kontextblog.herokuapp.com/
Netlify version: https://blog.kontext.app/

fyi I used this tutorial to set everything up: https://medium.com/@zingzai/create-a-free-jamstack-blog-using-ghost-heroku-and-netlify-7727d82ae56b

Thanks for the great template anyway!! :)

**Comment by styxlab** [comment]
If you run `gatsby-starter-try-ghost` on a cloud provider its better to provide your content API keys in environment variables. Go to your site in Netlify, then _Site Settings -> Build & deploy -> Environment -> Edit_ variables:

```
GHOST_API_URL           <your url>
GHOST_CONTENT_API_KEY   <your key>
```

In principle, providing a `.ghost.json` in the root of `gatsby-starter-try-ghost` works too, but if you are using a public git repository you should not place your keys in the repo.  For security reasons, `.ghost.json` is part of `.gitignore` and is not automatically transferred to your repo when committing changes. I suspect this is the reason why your current setup is not working (you do not have a `.ghost.json` file in your public git repo).

**Comment by styxlab** [comment]
I just cloned your fork `https://github.com/seichris/gatsby-starter-try-ghost` and build your project locally and your content is picked up correctly:

![image](https://user-images.githubusercontent.com/19638263/88909912-fd322400-d25b-11ea-9011-5ee4b06c2fdf.png)

So this should work on Netlify too. Maybe you deployed the wrong repo to Netlify (https://github.com/seichris/gatsby-theme-try-ghost instead of https://github.com/seichris/gatsby-starter-try-ghost?).

By the way, the theme is for development and not intended to be deployed.

**Comment by seichris** [comment]
Thanks! It works with the env variables!

Also I changed the keys and will leave them private :)
