### ISSUE TITLE
Netlify Build Times

### ISSUE THREAD

**Issue by JudicialDomicide** [styxlab/gatsby-theme-try-ghost#179]
Not so much a bug or issue but I was wondering if there was a way to reduce the build times in Netlify.

I've noticed that making a basic change on the backend ghost like correcting a typo may take just over 2 mins to build.
Likewise when pushing a basic change to siteConfig.js it can take around 2.5minutes to 3 minutes.

I'm looking at this currently but unsure as to whether it will help.
https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify-cache/

**Comment by styxlab** [comment]
During development of [gatsby-theme-try-ghost](https://github.com/styxlab/gatsby-theme-try-ghost/) I made extensive build time test and I am happy to share with you some of my observations. 

First of all, for a lot of projects, a couple of minutes for re-generating a static site is completely acceptable - don't spend time optimizing this any further *now*. Why? Focus of all static site builder projects is to improve build times in the future, so most likely you will get further speed-ups for free in the future.

If you really need fast builds, either because you have a really large site or because you need to do a lot of frequent content edits that must be published immediately, here are some practical suggestions that work well with this project (and other Gatsby projects too):

- Use Gatsby Cloud for building your site (and use their feature to deploy to Netlify). With this, a typical site should build in less than a minute. Why? Gatsby Cloud is optimized for Gatsby projects and it uses the cache most effectively. You will get improvements with netlify cache, but you will not reach the level of Gatsby Cloud. Read my [article on Netlify](https://community.netlify.com/t/gatsby-incremental-builds-on-netlify/16571) for more in-depth information.

- Make use of incremental builds on Gatsby Cloud and read the [Jamify incremental build article](https://www.jamify.org/2020/06/13/incremental-builds-with-jamify/) for more details. Warning: I consider incremental builds on Gatsby Cloud still experimental - there are still some frustrating hickups that you should be aware of.

- Why do Gatsby sites take time to build? The most computational expensive part is to generate images for lazy-loading. That means that if build times are more important to you than optimized images, you may want to refrain from using the [gatsby-rehype-inline-images](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-rehype-inline-images) plugin. Furthermore, you can also switch-off image processing for feature images (set the option `gatsbyImages: false` in `SiteConfig.js`). Of course, you will then loose all the great lazy loading images features!

Note that I am currently working on A Jamify Cloud solution that will take care of image processing, so you will get fast builds in the future that include all image optimizations. Stay tunded!

**Comment by styxlab** [comment]
Closed as answered.
