### ISSUE TITLE
Google Page speed score low 60 

### ISSUE THREAD

**Issue by marcoSven** [styxlab/gatsby-theme-try-ghost#203]
What happened to the page speed score of 100 mentioned in the readme?

Using the demo site I get a score of 62 

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.jamify.org%2F

**Comment by tobimori** [comment]
Lighthouse had a new major release with stricter guidelines. Also depends on what you're using for those tests.

**Comment by styxlab** [comment]
Just adding to @tobimori... The new Google Lighthouse 6 scores have hit Gatsby projects unexpectedly, due to totally different metrics. However, Gatsby is working hard to also look favorable with the new metrics. There is a new `gatsby-image` plugin that looks promising (see https://github.com/gatsbyjs/gatsby/issues/24332).

Once Google has fully settled on the new metrics and Gatsby has incorporated it's speed improvements into the core, I will also update the LH scores on this project. In the meantime, you can get better scores by disabling the blur-up effect in images (there is an option for that in the config).

**Comment by marcoSven** [comment]
Thank you @styxlab that is exciting.
