### ISSUE TITLE
gatsby-theme-try-ghost doesn't work Subscribe to Newsletter URL changed

### ISSUE THREAD

**Issue by udaya2899** [styxlab/gatsby-theme-try-ghost#224]
Send magic link URL has been changed to

`{blog_url}/ghost/api/canary/members/send-magic-link`

In the plugin, it is used as `/members/api/send-magic-link`

**Comment by styxlab** [comment]
@udaya2899 Thanks so much for reporting and for the PR. There are however some issues with this as the endpoint depends on the specific ghost version (btw, do you know the exact version when this has changed?). This means we need to support both endpoints as we cannot assume a specific Ghost version here. I see the following options:

1. make the endpoint configurable instead of hard-coded.
2. make the program more clever: try the newer endpoint first and revert to the second one if it fails.

My preference is leaning towards the second option. Would you like to enhance the PR in that way?

On a minor note, your eslint/prettier config reformatted the file. This project is not using prettier at the moment and only enforces eslint-rules. Please ensure that your PRs only contain actual changes not reformatting changes.

**Comment by udaya2899** [comment]
@styxlab Thanks for the clarity. I am using ghost 3.2.0. Members API is so unstable that ghost hasn't even included it in their docs. I did what they suggested in the ghost forum [here](https://forum.ghost.org/t/creating-members-with-the-api/12792) and found the updated route through the Networks tab.

Since this API is highly unstable and not documented at all, I suggest we give it customizable to the user. All this until it becomes stable and is documented.

I'd also like to hear your approach on point no.2. 

About the prettier: Noted. Will make sure when I update the PR.

**Comment by styxlab** [comment]
The second approach could be implemented in handleSubmit:
```
    handleSubmit(event) {
        event.preventDefault()

        const cmsUrl = this.props.url
        const postURL = `${cmsUrl}/members/api/send-magic-link/`

        const values = {
            email: this.state.value,
            emailType: `subscribe`,
            labels: [],
        }

        fetch(postURL, {
            method: `POST`,
            mode: `cors`,
            headers: { 'Content-Type': `application/json` },
            body: JSON.stringify(values),
        }).then(() => {
            this.setState({ message: `success` })
        }).catch(() => {
            // Fetch a second time with different endpoint
            this.setState({ message: `error` })
        })
    }
```
Basically you could fetch a second time on the other endpoint, if you reach the catch block.

**Comment by styxlab** [comment]
Btw, I cannot find the new route you are postingin the Ghost repositors. My [search](https://github.com/search?q=org%3ATryGhost+%2Fmembers%2Fsend-magic-link&type=code) only yields the old endpoint. Where can I find the code for the new endpoint?

**Comment by styxlab** [comment]
I also traced the latest Ghost version `v3.37.1`:

![image](https://user-images.githubusercontent.com/19638263/98377878-a18aea00-2045-11eb-911a-1ae31373e774.png)

and when I enter an email in the subscribe window fields, the network tabs shows me:

![image](https://user-images.githubusercontent.com/19638263/98377669-68527a00-2045-11eb-9386-eb32c78d2d05.png)

I am not sure where the info comes from, but I think the magic link has not chaged.

**Comment by styxlab** [comment]
To the best of my knowledge, the magic link has not changed. Please let me know if you disagree.
