### ISSUE TITLE
Problem with featureImageSharp

### ISSUE THREAD

**Issue by AmadeuszGK** [styxlab/gatsby-theme-try-ghost#240]
Hi, I have a problem with featureImageSharp. My graphql code looks like this:
```
{
  allGhostPost(sort: {fields: published_at, order: DESC}, limit: 1, filter: {tags: {elemMatch: {name: {ne: "Kariera"}}}}) {
    edges {
      node {
        tags {
          id
        }
        title
        url
        slug
        published_at(formatString: "")
        codeinjection_head
        feature_image
        featureImageSharp
      }
    }
  }
}
```

and featureImageSharp return string only.

**Comment by styxlab** [comment]
Welcome @AmadeuszGK! Could you please link to a reproducible example? In the case of GraphQL problems: A description on how to see the problem in the GarphQL explorer could also help.

**Comment by PawelBaranowski** [comment]
Hi @styxlab!
I'm @AmadeuszGK's coworker. We're experiencing a problem with `gatsby-plugin-ghost-images`. I created a reproducible example in https://github.com/PawelBaranowski/gatsby-plugin-ghost-images-issue-240. It's a fresh gatsby site from `gatsbyjs/gatsby-starter-default`.
As can be seen in https://github.com/PawelBaranowski/gatsby-plugin-ghost-images-issue-240/commit/e149a6f82f3c632e01d9d6fa701f371f64da566e I only updated `gatsby` to `2.27.0` which is required by said plugin, installed current `gatsby-source-ghost` and `gatsby-plugin-ghost-images` and put settings for both in `gatsby-config.js`.

Now the expected result is to have a whole tree of nodes under `featureImageSharp`, whereas direct GraphQL query
```graphql
query MyQuery {
  ghostPost {
    featureImageSharp
  }
}
```
returns only
```json
{
  "data": {
    "ghostPost": {
      "featureImageSharp": "fdf57c8d-9179-5c1b-9382-d3c85861a0bd"
    }
  }
}
```
`fdf57c8d-9179-5c1b-9382-d3c85861a0bd` happens to be a file node, because
```graphql
query MyQuery {
  file(id: {eq: "fdf57c8d-9179-5c1b-9382-d3c85861a0bd"}) {
    id
    childImageSharp {
      original {
        src
      }
    }
  }
}
```
returns
```json
{
  "data": {
    "file": {
      "id": "fdf57c8d-9179-5c1b-9382-d3c85861a0bd",
      "childImageSharp": {
        "original": {
          "src": "/static/post-image-1e1bbde82fec29064e1574a188a1f7e2.png"
        }
      }
    }
  }
}
```
Is this a known problem and - more importantly - is there a fix?

**Comment by styxlab** [comment]
The reason you are not getting the images into the `featureImageSharp` nodes is that you are using the wrong stack. First of all, this plugin only works in conjunction with [gatsby-source-try-ghost](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-source-try-ghost) not with `gatsby-source-ghost`.

Note that the `gatsby-plugin-ghost-images` plugin is designed to work with [gatsby-starter-try-ghost](https://github.com/search?q=gatsby-starter-try-ghost). Although it should work in other contexts, you are on your own if you run into issues. I can only support usage within [gatsby-starter-try-ghost](https://github.com/search?q=gatsby-starter-try-ghost) and [gatsby-theme-try-ghost](https://github.com/styxlab/gatsby-theme-try-ghost).

I hope these comments point you in the right direction!

**Comment by PawelBaranowski** [comment]
@styxlab thanks for making it crystal clear!

**Comment by PawelBaranowski** [comment]
On more thing to note though:

> First of all, this plugin only works in conjunction with gatsby-source-try-ghost
> Note that the gatsby-plugin-ghost-images plugin is designed to work with gatsby-starter-try-ghost

These statements aren't *at all* outlined in plugin's README:
https://www.gatsbyjs.com/plugins/gatsby-plugin-ghost-images/

**Comment by styxlab** [comment]
Thanks for the suggestion, I added a note to the README of the plugin. I also made a PR to `gatsby-plugin-ghost-images-issue-240` that shows that your example works with `gatsby-source-try-ghost`.

**Comment by PawelBaranowski** [comment]
Thanks a million!

**Comment by AmadeuszGK** [comment]
Thanks a lot!
