### ISSUE TITLE
Ghost post is not reflecting when working in dev mode

### ISSUE THREAD

**Issue by saurabhjain06** [styxlab/gatsby-theme-try-ghost#274]
I am working in localhost environment. Whenever I write a new post, I have to rebuild the Gatsby project by triggering command _yarn clean; yarn develop_.
Is it expected behaviour?
Whenever I upload the production build to netlify or any other provider, do I need to rebuild each time?
Note:- I am planning to keep my ghost at localhost for production env also.

**Comment by styxlab** [comment]
Hi @saurabhjain06!

1. `yarn develop` should be enough in most cases.
2. Yes, you need to rebuild every time, but subsequent deploys should be faster with the Netlify caching module.

**Comment by saurabhjain06** [comment]
Thanks @styxlab,
I am still learning about static sites.. I think thats the concept behind static site is that with every change in content (post, theme, etc.), we need to rebuild and upload it to the servers. No matter dev or prod we have to rebuild. right?

**Comment by styxlab** [comment]
That's correct, but gatsby/netlify can utilize a cache, so subsequent builds are faster.

**Comment by saurabhjain06** [comment]
Thank @styxlab for this great theme and guidance.. I must say that both Gatsby and next themes are great, though couldn't able to build the nextjs theme in local server due to image optimisation issue with next export (I was planning to build locally and update it manually)..

**Comment by styxlab** [comment]
For the Next.js project: You can switch off the image optimizations in `appConfig.ts`. You can build everything local and deploy it with the CLIs from `vercel` or `netlify` from your local machine. However, in case of the Next.js project, you must have a Ghost CMS install that is publicly available in order to be able to access the images, because they are not sourced in during the build process. That's different from the Gatsby project where you have the option to that.

**Comment by saurabhjain06** [comment]
I think as of now I will keep Gatsby for my blog.. Thanks for your help..
