### ISSUE TITLE
API keys added to ghost,json

### ISSUE THREAD

**Issue by sawilde** [styxlab/gatsby-theme-try-ghost#288]
@styxlab In the repo https://github.com/styxlab/gatsby-starter-try-ghost there are some API keys in the ghost.json - just checking if that was intentional

**Comment by styxlab** [comment]
Thanks for noting, but those are just the keys for the demo content. They are needed in this repo, otherwise it would not be possible to show default content, if no user keys are provided. You can't do much with those keys, except scraping the content that's already published on the demo blog (that you could scrape anyways).
