### ISSUE TITLE
Remove the stub post by default in gatsby-transformer-rehype

### ISSUE THREAD

**Issue by Kerumen** [styxlab/gatsby-theme-try-ghost#52]
I was surprised to suddenly have on my blog a "Data Schema" post. After some research, I found that's [the stub](https://github.com/TryGhost/gatsby-source-ghost/blob/master/ghost-schema.js) Ghost uses to populate the GraphQL schema.

I noticed you added [a special condition in the `gatsby-transformer-rehype` filter](https://github.com/styxlab/gatsby-theme-try-ghost/blob/9d2ea7eff2e5d95008a3fcfcfa69011d70e5bb73/demo/gatsby-config.js#L60) to remove this stub post. Maybe we should add this by default?

If we do not use `gatsby-transformer-rehype`, we don't get the stub post (I don't know why), so it makes sense to remove it by default if we use the transformer?

**Comment by styxlab** [comment]
The `gatsby-transformer-rehype` plugin can be used in other projects totally unrelated to Ghost. That's why I chose to exclude the stub with the filter in the configuration. Other data sources might not need a stub for schema generation, they may use an explicit type system. I prefer generic code if possible.

It's actually funny that you see a "Data Schema" post. When I remove the stub condition, I do not get any additional posts. Initial motivation was not to waste time on stuff you don't need, which is especially important for image downloads (there are special stub images which are actually not just 1x1 pixel).

**Comment by Kerumen** [comment]
I understand, it makes sense! 

But why did you put the filter in the demo if you didn't see the stub post?

And I'd like to understand why with the source plugin only we don't have it but if we add the rehype plugin, it appears..

**Comment by styxlab** [comment]
Do you mind taking this discussion offline? I’ll write you an email later today!
